name: Run Unit Tests

on:
  push:
    branches:
      - '**'  # Executa em qualquer branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.302'  # Ajuste para a versão do .NET usada no projeto

    - name: Restore dependencies
      run: dotnet restore src/NizzolaActions/Nizzola.Domain.Tests/Nizzola.Domain.Tests.csproj

    - name: Build project
      run: dotnet build src/NizzolaActions/Nizzola.Domain.Tests/Nizzola.Domain.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      
      run: dotnet test src/NizzolaActions/Nizzola.Domain.Tests/Nizzola.Domain.Tests.csproj --no-build --verbosity detailed --logger "console;verbosity=detailed"